### ISSUE TITLE
Doc link is broken, examples missing

### ISSUE THREAD

**Issue by m3t4n01a** [deepmind/dm_env#4]
Hi there.

Looks promising, but there's no documentation and the examples consist of just one example.

Thanks!

**Comment by alimuldal** [comment]
Which link do you think is broken? The [doc link](https://github.com/deepmind/dm_env/blob/master/docs/index.md) in the main README seems to be correct.

Re: additional examples, you could take a look at [`bsuite`](https://github.com/deepmind/bsuite/tree/master/bsuite/environments) or [`dm_control`](https://github.com/deepmind/dm_control/blob/master/dm_control/rl/control.py). Is there something in particular that you feel is missing from the `catch.py` example? I'd prefer to keep this package quite minimalist, but we could add one or two more simple examples if they illustrate some specific points about the API that aren't covered by `catch.py`.

**Comment by m3t4n01a** [comment]
Yes, sorry about that, it seems that the docs are not displaying in my chrome but they do work in firefox. 

Thanks for the example links, I just thought that something is not right since the docs were not working and the examples were actually one example. 

Thanks for your help.
