### ISSUE TITLE
Could we get a git tag for the v1.5 release?

### ISSUE THREAD

**Issue by samuela** [deepmind/dm_env#8]
I just noticed that there's no git tag for the 1.5 release. It's not a huge deal, but it would be convenient for build systems for there to be a tag for each release. Could we get the v1.5 commit tagged as well?

**Comment by alimuldal** [comment]
Thanks, I'd added the tag but forgotten to push it.

**Comment by samuela** [comment]
Great, thanks @alimuldal !
